name: Test
on: [push, pull_request]
jobs:
  test_linux:
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        clion_version: [2019.3, 2020.1, 2020.2]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: actions/setup-python@v1
      - name: Get Conan
        run: pip install conan &&
          conan profile new default --detect &&
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: .gradle/downloads
          key: ${{ runner.os }}-${{ matrix.clion_version }}
      - name: Run tests
        run: ./gradlew test -PclionVersion=${{ matrix.clion_version }} --stacktrace
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: Test results (${{ matrix.clion_version }})
          path: build/reports/tests/test/
